src/ffi/lua.rs

Example program that won't compile before and will after:
```rust
let s = "return \"hello, world\"";
let mut state = lua::State::new();
//state.open_libs();
state.requiref("base", Some(lua::ffi::lualib::luaopen_base), false);
state.do_string(s);
println!("Returned: {:?}", state.check_string(2));
```
I really only know that this is true for `lua_CFunction`, but I'm assuming it's true for the others as well.
I can write a unit test for this if you'd like, just let me know where you'd like it.
Side note: I know that code is a bit odd, but using State::remove gives me linker errors, still working through that one.

C functions from lua for lua will be unsafe

---

src/wrapper/convert.rs

Fixes these errors on nightly:
~~~
src/wrapper/convert.rs:96:3: 96:50 warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
src/wrapper/convert.rs:96   fn from_lua(state: &mut State) -> Option<Self>;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/wrapper/convert.rs:96:3: 96:50 help: run `rustc --explain E0277` to see a detailed explanation
src/wrapper/convert.rs:96:3: 96:50 note: `Self` does not have a constant size known at compile-time
src/wrapper/convert.rs:96   fn from_lua(state: &mut State) -> Option<Self>;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/wrapper/convert.rs:96:3: 96:50 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details. …

Make ToLua require a sized type.

---

src/wrapper/state.rs

These functions can accept binary data (i.e. bytecode files), and the size can be derived from the length of the slice.

Change load_buffer and load_bufferx to take &[u8]

---

src/wrapper/state.rs

This is a self-explanatory convenience method intended to simplify checking for error statuses.

Add ThreadStatus::is_err() method

---

src/wrapper/state.rs

It seems to me that to allow calling `lua_close()` on a `&mut State` or on a non-owning `State` is to violate memory safety, since future attempts to use the `State` will almost certainly crash.
I'm not even sure the `close` method should exist, since `drop(state)` is sufficient to close an owned state before its scope ends.

Move lua_close call to Drop impl

---

src/lib.rs
src/wrapper/convert.rs

Removes dependency on the `convert` feature gate. Combined with #8, allows the library to compile on the stable channel.

Use deref coercions instead of .as_str()

---

src/wrapper/convert.rs
src/wrapper/state.rs

There are two related sets of changes in this patch:
1. Use the length-based variants of string functions where available. This reduces allocations and allows embedding nulls in strings.
2. Return references from string functions rather than owned Strings. This reduces allocations in cases where the returned result is not actually used, and the old behavior can be gained by appending `.to_owned()` to call sites.
* Based on the Lua source, `typename_of` and `typename_at` return `'static` strings.
I think the first point is pretty important, but the second is somewhat opinion-based. Thoughts?
Also, I should point out I here changed `to_str` to use `luaL_tolstring`, which converts more types of things to strings, and doesn't edit the stack in-place. Maybe this isn't desired.

Use length-based string functions and return &strs

---

src/ffi/lua.rs
src/ffi/luaconf.rs
src/ffi/mod.rs
src/lib.rs
src/wrapper/convert.rs
src/wrapper/state.rs

This patch has the goal of improving the appearance of the docs:
* Add missing documentation text and tweak some other text.
* Remove `pub` from modules whose members are all re-exported anyways.
* Change some type aliases to re-exports so that their docs are clearer.

Improve documentation and module layout

---

src/lib.rs
src/macros.rs

This would be used like:
```rust
fn tostring(lua: &mut State) -> i32 {
lua.check_any(1);
lua.to_str(1);
1
}
// other fns...
fn load_base_lib(lua: &mut State) {
lua.push_global_table();
lua.set_fns(&[
("tostring", lua_func!(tostring)),
// other fns...
]);
lua.pop(1);
}
```
Essentially, the burden of declaring the `unsafe extern "C" fn` and calling `State::from_ptr` is moved to the library, and clients can just declare `fn(&mut State) -> i32` without needing `unsafe` at all.
My investigations did not yield a way to provide this functionality except through a macro; I've tried to make it as ergonomic and safe as possible.

Add lua_func! macro to wrap safe functions as FFI functions

---

src/wrapper/convert.rs
src/wrapper/state.rs

Makes the index used for `FromLua` configurable, so that `State::to_type()` can be used on any value on the Lua stack. Fixes #27.

Configurable index for FromLua

---

Cargo.toml
build.rs

See #29 for important discussion.
The support is still not perfect, because `glue` is still compiled for the host platform and some of the types it produces may not match the target platform, but cross-compilation should at least be possible now.
I tested that the following configurations worked:
* Host `x86_64-pc-windows-gnu`, target same
* Host `x86_64-pc-windows-gnu`, target `i686-pc-windows-gnu`
* Host `x86_64-unknown-linux-gnu`, target same
* Host `x86_64-unknown-linux-gnu`, target `x86_64-pc-windows-gnu`

Improve buildscript for cross-compilation support

---

src/lib.rs
src/wrapper/state.rs

`load_library` is a correct way to load a built-in library, that exposes
the library to the lua code.
`preload_library` puts the built-in library to the `_PRELOAD` table so
lua code can `require` the module (whithout putting it into the globals)
Current `open_xxx` methods (except `open_libs`) are cumbersome to use. Since they just load a module and put it on stack. So you need to remember to store it into an appropriate name in the globals and pop it from stack. I believe that `open_xxx` methods should be deprecated.
The proper way to load modules (and the one used in this pull request) is here: http://www.lua.org/source/5.3/linit.c.html

Add `State.load_library` and `State.preload_library` methods

---

src/wrapper/state.rs

Stable PR for #48. Benchmarks not included here, but much like #52 there is not really a measurable difference in speed due to the change.
In the name of simplicity, the current implementation returns allocations with the same alignment as `usize` (4 or 8 bytes). According to my research, GCC and MSVC's mallocs both return allocations with an alignment double that, but it would require 16 bytes of overhead per allocation and additional bookkeeping I have not yet implemented to be able to satisfy this alignment. I don't know of any standard C type that actually requires 16-byte alignment.

Use Rust allocator (jemalloc) rather than system allocator

---

src/lib.rs

This library forces to use `libc` crate explicitly.
I have to use both `libc` and `lua` anytime, but I, really, need one everytime.

Re-export libc types

---

src/wrapper/state.rs

This PR fixes inaccuracies with `new_userdata_typed` example:
1. `set_metatable_from_registry` expects one argument only
2. `new_userdata_typed` needs `unsafe` block

Fix new_userdata_typed example

---

src/wrapper/state.rs

This PR implements `Hash` for `Reference`. It makes possible to use references as key of `HashMap` etc.

Derive Hash for Reference

---

src/lib.rs
src/wrapper/state.rs
tests/extra.rs

**This is IMPORTANT PR to prevent memory leaks or other dangerous consequences of using `extra` space.**
This PR improves extra space behavior with **nice backward compatibility**. Previous implementation has some imperfections:
1) Lua never call `drop` than `Extra` data lost in heap and memory leaks
2) We have to wrap `Extra` with `Mutex` explicitly everywhere
Every `Extra` have to implement `Send` because Lua does it. To use `Extra` we have to use `Mutex` explicitly everywhere. This makes code dirty with a lot of explicit mutex locking.
This PR store extra under `Mutex`. Profits:
1) It's safe to use it with Lua's threads (which takes copy of extra pointer by default)
2) This API makes user's code tidy and simpler (look for tests)
3) Works much faster than precise manual mutex control …

Use Mutex to protect Extra

---

.gitignore
Cargo.toml
build.rs

I have tested compilation with VS 2015 and VS 2017, on Ubuntu 16.04 (for regression) and Windows 10, both x86_64. The initial compilation of the crate has to be performed in the VS native tools environment for your target architecture, due to utilization of cl.exe and lib.exe, but once lua.lib has been generated, you can go back to your chosen environment until the crate has been cleaned. Alternatively, you can put the commands on %PATH%.

Add MSVC support

---

src/wrapper/state.rs

Add a lifetime parameter to lua_load, and use it to tie the lifetime of the `&[u8]` returned by the reader function/closure to the borrow lifetime of the Lua state (so the call to `lua_load`).
Note that I'm not completely sure this is correct, but it has solved my case where I really just wanted a version of `load_string` with the `chunkname` option added.  Feel free to reject if I'm just using it wrongly.
I call it a bit like this:
```rust
let mut done = false;
let code = code;  // &str
let empty = &b""[..];
let status = self.state.load(
|_| {
if done {
empty
} else {
done = true;
code.as_bytes()
}
},
source.into().unwrap_or("<string>"),
"bt");
```   
With the existing lifetimes, the reader callback is:
```rust
FnMut(&mut State) -> &[u8]
```
which I think effectively means that the …

Adjust the lifetimes for the lua_load callback

---

build.rs

build with `rustc v1.20.0` will show the following warning:
```
$ cargo build
Updating registry `https://github.com/rust-lang/crates.io-index`
Compiling gcc v0.3.54
Compiling bitflags v0.1.1
Compiling libc v0.2.32
Compiling lua v0.0.11 (file:///Users/poga/projects/spacer-workspace/rust-lua53)
warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
--> build.rs:136:22
|
136 |     let mut config = gcc::Config::new();
|                      ^^^^^^^^^^^^^^^^
|
= note: #[warn(deprecated)] on by default
Finished dev [unoptimized + debuginfo] target(s) in 11.25 secs
```
`gcc::Config` has been renamed to `gcc::Build`.

fix deprecated `gcc::Config`

---

src/wrapper/state.rs

This fixes a compile type error on arm, where `u8` is expected in this place.

Infer correct type, it is different on arm.
